[2025-10-06T03:21:30.833+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: forest_cover_training_pipeline.fetch_data scheduled__2025-10-06T03:06:00+00:00 [queued]>
[2025-10-06T03:21:30.843+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: forest_cover_training_pipeline.fetch_data scheduled__2025-10-06T03:06:00+00:00 [queued]>
[2025-10-06T03:21:30.843+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-10-06T03:21:30.854+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): fetch_data> on 2025-10-06 03:06:00+00:00
[2025-10-06T03:21:30.868+0000] {standard_task_runner.py:57} INFO - Started process 2197 to run task
[2025-10-06T03:21:30.874+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'forest_cover_training_pipeline', 'fetch_data', 'scheduled__2025-10-06T03:06:00+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/training_pipeline.py', '--cfg-path', '/tmp/tmpes1u60er']
[2025-10-06T03:21:30.882+0000] {standard_task_runner.py:85} INFO - Job 40: Subtask fetch_data
[2025-10-06T03:21:30.966+0000] {task_command.py:416} INFO - Running <TaskInstance: forest_cover_training_pipeline.fetch_data scheduled__2025-10-06T03:06:00+00:00 [running]> on host 20acfc9d0a87
[2025-10-06T03:21:31.107+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mlops_team' AIRFLOW_CTX_DAG_ID='forest_cover_training_pipeline' AIRFLOW_CTX_TASK_ID='fetch_data' AIRFLOW_CTX_EXECUTION_DATE='2025-10-06T03:06:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-06T03:06:00+00:00'
[2025-10-06T03:22:01.143+0000] {logging_mixin.py:154} INFO - [fetch_data] attempt 1 failed: HTTPConnectionPool(host='10.43.100.103', port=8080): Max retries exceeded with url: /data?group_number=6 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0xffff7b9610c0>, 'Connection to 10.43.100.103 timed out. (connect timeout=30)'))
[2025-10-06T03:22:03.618+0000] {logging_mixin.py:154} INFO - [fetch_data] GET http://10.43.100.103:8080/data?group_number=6 -> 200 (attempt 2/3)
[2025-10-06T03:22:03.669+0000] {logging_mixin.py:154} INFO - [fetch_data] batch=5 already exists in forest_raw â†’ skipping
[2025-10-06T03:22:03.670+0000] {taskinstance.py:1542} INFO - Batch 5 already ingested
[2025-10-06T03:22:03.681+0000] {taskinstance.py:1400} INFO - Marking task as SKIPPED. dag_id=forest_cover_training_pipeline, task_id=fetch_data, execution_date=20251006T030600, start_date=20251006T032130, end_date=20251006T032203
[2025-10-06T03:22:03.738+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-10-06T03:22:03.764+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
