[2025-10-06T04:00:03.789+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: forest_cover_training_pipeline.fetch_data scheduled__2025-10-06T03:54:00+00:00 [queued]>
[2025-10-06T04:00:03.794+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: forest_cover_training_pipeline.fetch_data scheduled__2025-10-06T03:54:00+00:00 [queued]>
[2025-10-06T04:00:03.794+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-10-06T04:00:03.800+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): fetch_data> on 2025-10-06 03:54:00+00:00
[2025-10-06T04:00:03.805+0000] {standard_task_runner.py:57} INFO - Started process 3616 to run task
[2025-10-06T04:00:03.808+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'forest_cover_training_pipeline', 'fetch_data', 'scheduled__2025-10-06T03:54:00+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/training_pipeline.py', '--cfg-path', '/tmp/tmpou0nl4tj']
[2025-10-06T04:00:03.811+0000] {standard_task_runner.py:85} INFO - Job 68: Subtask fetch_data
[2025-10-06T04:00:03.845+0000] {task_command.py:416} INFO - Running <TaskInstance: forest_cover_training_pipeline.fetch_data scheduled__2025-10-06T03:54:00+00:00 [running]> on host 20acfc9d0a87
[2025-10-06T04:00:03.892+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mlops_team' AIRFLOW_CTX_DAG_ID='forest_cover_training_pipeline' AIRFLOW_CTX_TASK_ID='fetch_data' AIRFLOW_CTX_EXECUTION_DATE='2025-10-06T03:54:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-06T03:54:00+00:00'
[2025-10-06T04:00:03.930+0000] {logging_mixin.py:154} INFO - [fetch_data] GET http://10.43.100.103:8080/data?group_number=6 -> 400 (attempt 1/3)
[2025-10-06T04:00:03.930+0000] {logging_mixin.py:154} INFO - [fetch_data] attempt 1 failed: 400 Client Error: Bad Request for url: http://10.43.100.103:8080/data?group_number=6
[2025-10-06T04:00:05.985+0000] {logging_mixin.py:154} INFO - [fetch_data] GET http://10.43.100.103:8080/data?group_number=6 -> 400 (attempt 2/3)
[2025-10-06T04:00:05.988+0000] {logging_mixin.py:154} INFO - [fetch_data] attempt 2 failed: 400 Client Error: Bad Request for url: http://10.43.100.103:8080/data?group_number=6
[2025-10-06T04:00:09.044+0000] {logging_mixin.py:154} INFO - [fetch_data] GET http://10.43.100.103:8080/data?group_number=6 -> 400 (attempt 3/3)
[2025-10-06T04:00:09.045+0000] {logging_mixin.py:154} INFO - [fetch_data] attempt 3 failed: 400 Client Error: Bad Request for url: http://10.43.100.103:8080/data?group_number=6
[2025-10-06T04:00:09.046+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/training_pipeline.py", line 98, in fetch_data_from_api
    r.raise_for_status()
  File "/home/airflow/.local/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://10.43.100.103:8080/data?group_number=6
[2025-10-06T04:00:09.072+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=forest_cover_training_pipeline, task_id=fetch_data, execution_date=20251006T035400, start_date=20251006T040003, end_date=20251006T040009
[2025-10-06T04:00:09.095+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 68 for task fetch_data (400 Client Error: Bad Request for url: http://10.43.100.103:8080/data?group_number=6; 3616)
[2025-10-06T04:00:09.121+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-10-06T04:00:09.149+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
